- src/.vuepress/theme/components/blog/LinkCard.vue
> fix: use https on youtube thumbnail image url

- src/_blog/005-ipfs-0-4-0-released.md
- src/_blog/010-go-ipfs-0-4-4-released.md
- src/_blog/014-pubsub.md
- src/_blog/016-go-ipfs-0-4-10.md
- src/_blog/023-go-ipfs-0.4.14.md
Posts with this issue:
- https://blog.ipfs.io/25-pubsub/
- https://blog.ipfs.io/34-go-ipfs-0.4.14/
- https://blog.ipfs.io/27-go-ipfs-0-4-10/
- https://blog.ipfs.io/21-go-ipfs-0-4-4-released/
- https://blog.ipfs.io/14-ipfs-0-4-0-released/
Fixed:
- https://bafybeig6lq3oj6btpqfmmnfletgenfpf6sluzhazypwi6u2bu2wqvv7dtm.on.fleek.co/25-pubsub/
- https://bafybeig6lq3oj6btpqfmmnfletgenfpf6sluzhazypwi6u2bu2wqvv7dtm.on.fleek.co/34-go-ipfs-0.4.14/
- https://bafybeig6lq3oj6btpqfmmnfletgenfpf6sluzhazypwi6u2bu2wqvv7dtm.on.fleek.co/27-go-ipfs-0-4-10/
- https://bafybeig6lq3oj6btpqfmmnfletgenfpf6sluzhazypwi6u2bu2wqvv7dtm.on.fleek.co/21-go-ipfs-0-4-4-released/
- https://bafybeig6lq3oj6btpqfmmnfletgenfpf6sluzhazypwi6u2bu2wqvv7dtm.on.fleek.co/14-ipfs-0-4-0-released/
> fix: remove extra newlines in 25-pubsub blog post

- src/.vuepress/theme/styles/components/typography.css
Closes https://github.com/ipfs/ipfs-blog/issues/122.
Changes blockquote left border gradient to match page header.
> fix: blockquote color CSS

- src/_blog/ipfs-and-igalia-collaborate-on-dweb-in-browsers.md
Fixes 404 on https://blog.ipfs.io/2021-01-15-ipfs-and-igalia-collaborate-on-dweb-in-browsers/
Ref: https://github.com/ipfs/in-web-browsers/issues/144#issuecomment-817330819
> fix: incorrect metadata field

- src/_blog/086-ipfs-in-opera-for-android.md
- src/_blog/ipfs-in-opera-touch-on-ios.md
Latest version from the old blog: https://github.com/ipfs/blog/blob/master/content/post/123-opera-ios-and-ipfs.md
Web Archive view: https://web.archive.org/web/20210209172608/https://blog.ipfs.io/2021-02-08-opera-ios-and-ipfs/
The version in the new re-platformed blog is the first draft pushed to the old blog ipfs/blog and this PR brings it up to date with the previously posted version.
> Content update: IPFS in Opera Touch for iOS 

- package-lock.json
- package.json
- src/.vuepress/config.js
Adds [vuepress-plugin-chunkload-redirect](https://github.com/cwaring/vuepress-plugin-chunkload-redirect) to handle chunkload errors transparently.
> feat: add vuepress-plugin-chunkload-redirect

- src/.vuepress/theme/layouts/BlogPost.vue
- src/.vuepress/theme/styles/index.css
The video embeds had fixed width and height, so on smaller devices the window would get an horizontal scroll. On some browsers the navigation would stick to the right completely hidden from the user.
You can see this issue in one of the latest blog posts: https://blog.ipfs.io/2021-04-14-scaling-ethereum/
I thought of adding the [`tailwindcss-aspect-ratio`](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) plugin, but that would require a parent element.
To fix this I simply used `aspect-ratio` property with fallback to fixed heights with one media query breakpoint.
On browsers that don't support aspect ratio, there is a specific range of screen sizes where it looks weird but for that we'd need a smaller breakpoint to get all the sizes right. But it doesn't seem to affect a lot of …
> Video embeds and code blocks break layout by adding horizontal scroll to window on smaller devices

- .github/workflows/scheduled-publishing.yml
Build trigger was not working because fleek's github action expects a final build directory to be sent to be deployed. Instead we just want to trigger a build in fleek so we don't need to maintain multiple build setups.
This PR switches from using the github action to Fleek's http API.
> fix: use fleek api instead to trigger the build

- src/_blog/js-ipfs-0.55.0-greatly-improves-type-definitions.md
Fixes broken markdown formatting in the "new features" section of the js-ipfs 0.55.0 post.
**before**
**after**
> fix: formatting of new features in js-ipfs-0.55.0

- .github/workflows/sync-staging.yml
This PR adds the workflow file `sync-staging.yml` that is triggered on new `main` changes and simply updates the `staging` branch with `main`.
It only fast-forwards, meaning it doesn't merge diverging `main` and `staging`. This ensures that no content staging PR gets bloated with any `main` changes.
Closes #200
> chore: add sync staging workflow file

- src/.vuepress/theme/components/blog/PostMeta.vue
- src/.vuepress/theme/components/blog/PostMetaTitle.vue
Adds outbound icon to external post titles.
Displays in all cases except when a line title is clamped. I feel like this is a reasonable tradeoff considering the extra performance overhead of processing every title based on custom pixel breakpoints and also the regression we might get from SEO by trimming the post titles and separating into blocks.
alt to: #217
closes: #213
> feat: add PostMetaTitle for external links

- scripts/data/news.json
Just noticed a tiny typo in the `news.json` file.
> fix: remove typo from static news.json

- src/_blog/2021-05-31-distributed-wikipedia-mirror-update.md
Fixes a broken link in https://blog.ipfs.io/2021-05-31-distributed-wikipedia-mirror-update/
> fix: broken link in Wikipedia blog post

- package-lock.json
- package.json
- src/.vuepress/theme/styles/components/index.css
- src/.vuepress/theme/styles/components/typography.css
- src/.vuepress/theme/styles/index.css
- src/.vuepress/theme/tailwind.config.js
- Bumps the `tailwindcss` version
- Moves all the typography styles to the tailwind config
Note: I tried to move the code for the pseudo element inside the [typograpyhy.css](https://github.com/ipfs/ipfs-blog/blob/chore/improve-typography/src/.vuepress/theme/styles/components/typography.css) file to the tailwind config but it doesn't work 🤷‍♂️
> chore: move all the typography styles to the tailwind config

- src/_blog/releasenotes.md
This PR adds a link for release notes for go-ipfs 0.9.1.
cc @aschmahmann @emilymvaughan - now you don't need to do this!
> Add release notes link: go-ipfs v0.9.1

- src/.vuepress/theme/components/blog/Comments.vue
Comments on some pages  are  broken due to the lack of leading `/` in permalink, for example: https://blog.ipfs.io/2021-06-17-opensea-ipfs-filecoin/
While we could add it everywhere,  or remove it and add it in the JS snippet responsible for embedding, both fixes are not future-proof, because someone could add a permalink that breaks the thing for a new blogpost.
This PR aims to add normalization that makes sure every permalink works, 
no matter if it is defined with or without leading slash.
By leveraging `URL` behavior it solves problem described on [meta.discourse.org](https://meta.discourse.org/t/referer-with-domain-name-in-the-slug-breaks-comments-embed/204807/4?u=lidel) without breaking existing comment threads.
Permalinks with leading slash and without it will work the same, …
> fix: comments on permalinks without slash

- src/.vuepress/theme/components/blog/Comments.vue
@andyschwab this publishes the fix from `staging` to `main`
- For context, see https://github.com/ipfs/ipfs-blog/pull/325#issue-746940478
- Confirmed to work as expected on https://ipfs-blog-staging.on.fleek.co
> fix: comments with permalinks without slash (#325)

- src/_blog/what-is-ipld.md
Some more edits considered during https://github.com/ipfs/ipfs-blog/pull/347 .
I'm not sure I'm preserving the original intention of this section or not, but I tried to connect the short story about IPFS and UnixFS back to decoding and why CIDs matter (as introduced by the first sentence of the section) a bit more.
> additional efforts to clarify unixfs vs codecs

- package-lock.json
- package.json
- src/.vuepress/config.js
- src/.vuepress/plugins/canonical.js
- src/README.md
After discoving that the plugin we're using [isn't working](https://github.com/IOriens/vuepress-plugin-canonical/issues/2) and that we don't have any canonical tags on the blog, I fixed it by building a small plugin.
- Remove non functioning canonical plugin
- Add custom plugin to add the canonical tag to blog posts
One of the quick ways to test/check canonical tags is https://seominion.com/ a browser plugin that you can run on any page. 
If you run it on https://blog.ipfs.tech/ currently, you will see there's none.
This PR fixes it for every blog post while still allowing to override via the `frontmatter.canonicalUrl`
> SEO: Add default canonical links to pages

- src/_blog/state-of-ipfs-in-js.md
I think the `b` in `#js-ipfs-in-a-browser-context` needs to be lowercase for the link to work
> state-of-ipfs-in-js: fix jumping anchor links

- src/_blog/releasenotes.md
This PR adds a release note for the v0.18.0 Kubo release.
The formatting diff is introduced because I used [yq](https://mikefarah.gitbook.io/yq/) to automate the release note creation.
> Add release note: Kubo v0.18.0

- src/_blog/state-of-ipfs-in-js.md
This PR updates references from Pomegranate to Helia.
> fix: rename Pomegranate to Helia in js blog post

- src/_blog/2023-05-js-ipfs-deprecation-for-helia.md
This is a blog post accompanying the js-ipfs deprecation work that is active at https://github.com/ipfs/js-ipfs/issues/4336
We were originally going to do a discuss.ipfs.tech post ([proposed text](https://www.notion.so/pl-strflt/2023Q2-js-ipfs-Deprecation-c84d5d4f661044198ba6e63bf0a34790?pvs=4#665338dad2ae4408abde8e5f88f2d7ec)).  Doing this as a blog entry will cause the discuss.ipfs.tech post to be generated while getting broader reach for the message.
Switching from a discuss.ipfs.tech post to a blog entry came to mind when thinking about the next IPFS Newsletter.  I know we can manually submit newsletter additions, but this should get it scooped up by default.
(With deprecations, the more expansive the communication the better to avoid surprises.)
Ideally yes, but I'm just taking the …
> js-ipfs deprecation - replaced by Helia

- src/_blog/introducing-reframe.md
- src/_blog/state-of-ipfs-in-js.md
- src/_blog/welcome-to-ipfs-news-184.md
- src/_blog/welcome-to-ipfs-news-186.md
This PR takes care of some outdated blogposts pointing at legacy Reframe. 
Added disclaimers to reduce confusion when someone googles it or follows old links.
Context: https://github.com/ipfs/kubo/issues/9479
> chore: finish reframe deprecation

- src/_blog/shipyard-hello-world.md
This PR contains small change against #677 (separate PR for easier review by @mishmosh  / @aschmahmann / @bethanymarz)
The table felt useless, unless one knew what these made-up names mean.
I think we should reorder and add useful links and annotations (this PR), 
allowing reader to explore details of each area.
> ![Screenshot 2024-04-05 at 17-49-35 IPFS   libp2p Devs Go Independent Meet Interplanetary Shipyard](https://github.com/ipfs/ipfs-blog/assets/157609/f9c71ca1-ef98-4a7c-8e01-246b0b0bf819)
> ![Screenshot 2024-04-05 at 17-45-36 IPFS   libp2p Devs Go Independent Meet Interplanetary Shipyard](https://github.com/ipfs/ipfs-blog/assets/157609/7d4286bb-1747-44b0-a45b-ff8e558fcef1)
> chore: improve table of Shipyard projects

- src/_blog/shipyard-2024.md
github links are a pain (it seems the branch was deleted when merged to main)
> Link typo in shipyard-2024.md (Shipyard improving ipfs on the web.md)

- .github/workflows/build-and-deploy.yml
This PR enables fork builds to also access secrets for preview builds. There's the risk of secrets getting exposed if the workflows are modified. This can only be circumvented by requiring manual approval for workflow runs.
> ci: run workflow with secrets for forks too
