src/.vuepress/theme/layouts/BlogPost.vue

- Changes the condition that is used to show the Discourse comments, enabling it for all the IPFS domains 
Closes #80

fix: update discourse condition to show comments

---

src/.vuepress/theme/components/base/LazyImage.vue

- Removes the background for all the lazy images except the placeholders
Closes #114

fix: remove lazy image background

---

src/.vuepress/theme/layouts/Blog.vue

fix: remove load more observer on destroy

---

src/.vuepress/config.js
src/.vuepress/plugins/vuepress-plugin-speedcurve/enhanceAppFiles.js
src/.vuepress/plugins/vuepress-plugin-speedcurve/index.js

Setup speedcurve script

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/js-ipfs-0.55.0-greatly-improves-type-definitions.md
src/_blog/releasenotes.md

Adds blog post for `js-ipfs@0.55.0`

Update from Forestry.io Alex Potsides created src/_blog/js-ipfs-0.55.0-greatly-improves-type-definitions.md

---

package-lock.json
package.json

Revert "chore(deps-dev): bump eslint-plugin-import from 2.23.3 to 2.23.4"

---

src/.vuepress/theme/components/blog/VideoModalContent.vue
src/.vuepress/theme/tailwind.config.js

Tweaks styling for `<h4>` and `<h5>` for better visual hierarchy overall.

style: tweak h4/h5 styling for better hierarchy

---

scripts/data/news.json
scripts/data/videos.json
scripts/latest-posts.js
src/.vuepress/theme/components/blog/ActiveTags.vue
src/.vuepress/theme/components/blog/NewsletterForm.vue
src/.vuepress/theme/components/blog/SearchCategoriesAndTags.vue
src/.vuepress/theme/layouts/Blog.vue
src/.vuepress/theme/layouts/ImageCrop.vue
src/.vuepress/theme/tailwind.config.js

- Adds some UI improvements to match styles on the replatformed website
- Adds a `news.json` file with the 3 latest news added to the blog ([context](https://github.com/ipfs/ipfs-website/issues/11#issuecomment-853163754))
- Adds a `videos.json` file with the 2 latest videos added to the blog ([context](https://github.com/ipfs/ipfs-website/issues/11#issuecomment-853163754))

fix: add ui improvements

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/a-guide-to-ipfs-connectivity-in-web-browsers.md

This is a blog post to help assist people in getting started using browser js-ipfs. I linked the original HackMD here as some features I wasn't entirely sure how I should move them over (namely Table of Contents, and the little info boxes), I tried to keep it looking nice anyways :).
I set the date for June 21 as I wasn't sure what I should set.
Repo For Website: https://github.com/TheDiscordian/browser-ipfs-chat
Gist for Python script: https://gist.github.com/TheDiscordian/51962fea72f8d5a5c3bba79dd7009e1c
Original HackMD: https://hackmd.io/@Discordian/S1gBLg5Id/edit
Edit: P.S. No idea why the user shows up as one of my old accounts, redstarcoder.

Blog Post: A Guide to IPFS Connectivity in Web Browsers

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/a-guide-to-ipfs-connectivity-in-web-browsers.md

Starts with @TheDiscordian's https://github.com/ipfs/ipfs-blog/pull/233 PR and adds the following:
- Copy edits (mainly standards from https://docs.ipfs.io/community/contribute/grammar-formatting-and-style/)
- Clarity edits

post: A guide to IPFS connectivity in browsers

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/interplanetary-timelessness-ipfs-filecoin-for-the-nft-long-haul.md

emily.vaughan@protocol.ai created src/_blog/interplanetary-timelessness-ipfs-filecoin-for-the-nft-long-haul.md

Add blog: Interplanetary Timelessness: IPFS & Filecoin for the NFT Long Haul

---

src/_blog/releasenotes.md

Jessica Schilling updated src/_blog/releasenotes.md

content: add go-ipfs 0.9.0 release notes link

---

src/_blog/go-ipfs-v0.9.0-has-been-released.md

Fix link to CAR specs

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/js-ipfs-0.56.0-upgrades-to-new-multiformats-stack-and-adds.car-import-export.md

@achingbrain, @rvagg, @vasco-santos — this is the new PR for your blog post. :pray:

Content: js-ipfs 0.56.0 blog post

---

src/_blog/releasenotes.md
src/_blog/welcome-to-ipfs-weekly-138.md
src/_blog/welcome-to-ipfs-weekly-139.md
src/_blog/welcome-to-ipfs-weekly-140.md
src/_blog/welcome-to-ipfs-weekly-141.md
src/_blog/welcome-to-ipfs-weekly-142.md
src/_blog/welcome-to-ipfs-weekly-143.md
src/_blog/welcome-to-ipfs-weekly-144.md
src/_blog/welcome-to-ipfs-weekly-145.md
src/_blog/welcome-to-ipfs-weekly-146.md
src/_blog/welcome-to-ipfs-weekly-147.md
src/_blog/welcome-to-ipfs-weekly-148.md

Alex Potsides updated src/_blog/releasenotes.md

Update from Forestry.io

---

src/_blog/releasenotes.md
src/_blog/welcome-to-ipfs-weekly-127.md
src/_blog/welcome-to-ipfs-weekly-128.md
src/_blog/welcome-to-ipfs-weekly-129.md
src/_blog/welcome-to-ipfs-weekly-130.md
src/_blog/welcome-to-ipfs-weekly-131.md
src/_blog/welcome-to-ipfs-weekly-132.md
src/_blog/welcome-to-ipfs-weekly-133.md
src/_blog/welcome-to-ipfs-weekly-134.md
src/_blog/welcome-to-ipfs-weekly-135.md
src/_blog/welcome-to-ipfs-weekly-136.md
src/_blog/welcome-to-ipfs-weekly-137.md

So @hsanjuan doesn't have to do it.

Add IPFS Cluster v0.14.1 release notes

---

src/_blog/about-500-000-in-prizes-and-grants-for-asia-hackathon-season-2021.md
src/_blog/nebulus-the-virtual-ipfs-network.md

emily.vaughan@protocol.ai updated src/_blog/about-500-000-in-prizes-and-grants-for-asia-hackathon-season-2021.md
emily.vaughan@protocol.ai updated src/_blog/nebulus-the-virtual-ipfs-network.md

Edits to Nebulus and AHS blog posts

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/welcome-to-ipfs-weekly-154.md

emily.vaughan@protocol.ai created src/_blog/welcome-to-ipfs-weekly-154.md

Add blog: IPFS Weekly 154

---

src/_blog/welcome-to-ipfs-weekly-154.md

emily.vaughan@protocol.ai updated src/_blog/welcome-to-ipfs-weekly-154.md

Fix IPFS Weekly 154 Link

---

src/_blog/releasenotes.md

emily.vaughan@protocol.ai updated src/_blog/releasenotes.md

Add release notes link: go-ipfs v0.10.0

---

src/_blog/what-is-ipld.md

This PR  applies minimal clarifications to avoid "IPFS has blockchain" meme.

fix: ipld clarifications around on-chain use

---

src/_blog/welcome-to-ipfs-weekly-165.md

emily.vaughan@protocol.ai updated src/_blog/welcome-to-ipfs-weekly-165.md

Edit to IPFS Weekly 165

---

src/_blog/ipfs-community-highlight-omnilingo.md

emily.vaughan@protocol.ai updated src/_blog/ipfs-community-highlight-omnilingo.md

Edit to OmniLingo post

---

src/_blog/fleek-a-web3-developer-hub-on-ipfs.md

emily.vaughan@protocol.ai updated src/_blog/fleek-a-web3-developer-hub-on-ipfs.md

Edit to Fleek blog post

---

src/_blog/filebase-building-web3-on-web3.md

emily.vaughan@protocol.ai updated src/_blog/filebase-building-web3-on-web3.md

Edit to Filebase blog

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/welcome-to-ipfs-news-179.md

emily.vaughan@protocol.ai created src/_blog/welcome-to-ipfs-news-179.md

Add blog: IPFS News 179

---

src/_blog/introducing-probelab.md

Some links were not imported correctly in MD and showing in a weird way in the actual post. This PR fixes these.

Fix markdown to render links

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/welcome-to-ipfs-news-180.md

emily.vaughan@protocol.ai created src/_blog/welcome-to-ipfs-news-180.md

Add blog: IPFS News 180

---

src/_blog/releasenotes.md

emily.vaughan@protocol.ai updated src/_blog/releasenotes.md

Add release notes: https://github.com/ipfs/kubo/releases/tag/v0.15.0

---

src/.vuepress/config/head.js

See context https://github.com/ipfs/ipfs-docs/pull/1257#issuecomment-1232043651

Add plausible analytics

---

src/.vuepress/theme/styles/components/index.css
src/_blog/2023-01-10-announcing-pin-tweet-to-ipfs.md

https://bafybeiebaihvybc3hgjeju2wz5fcg4ggsfeiepjuccqguyiznlcbpthpom.on.fleek.co/announcing-pin-tweet-to-ipfs/

feat: add cta buttons and make sources links

---

.forestry/front_matter/templates/blog-post.yml
src/_blog/welcome-to-ipfs-news-191.md

Crystal Mills created src/_blog/welcome-to-ipfs-news-191.md

Add blog: Welcome to IPFS News 191

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.18.1

Update Kubo: v0.18.1

---

src/_blog/videos.md

This adds a video link to the first episode of This Month in IPFS

feat: add this month in IPFS video

---

src/_blog/welcome-to-ipfs-news-192.md

Description of the blog post needed to be tweaked.

Change description of welcome-to-ipfs-news-192.md

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.19.1

Update Kubo: v0.19.1

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.19.2

Update Kubo: v0.19.2

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.20.0

Update Kubo: v0.20.0

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.21.0

Update Kubo: v0.21.0

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.22.0

Update Kubo: v0.22.0

---

src/.vuepress/config/head.js

This PR fixes the plausible script which was being loaded indirectly but was broken for a while.

fix plausible script

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.23.0

Update Kubo: v0.23.0

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.24.0

Update Kubo: v0.24.0

---

src/.vuepress/theme/components/blog/NewsletterForm.vue
src/.vuepress/theme/layouts/Blog.vue

Fixes https://github.com/ipfs/ipfs-blog/issues/635

Fix newsletter form

---

src/_blog/videos.md

This PR adds the older this month in IPFS videos and the new Built with IPFS video from today on Mintter.

add videos

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.25.0

Update Kubo: v0.25.0

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.26.0

Update Kubo: v0.26.0

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.29.0

Update Kubo: v0.29.0

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.30.0

Update Kubo: v0.30.0

---

src/_blog/releasenotes.md

This PR updates Kubo to v0.31.0

Update Kubo: v0.31.0

---

src/_blog/releasenotes.md

cc https://github.com/ipfs/kubo/issues/10547

chore: kubo v0.32

---

src/_blog/releasenotes.md

https://github.com/ipfs/kubo/issues/10580

chore: kubo 0.33
